import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:provider/provider.dart';
import 'dart:convert';

import 'model.dart';

class MatchInfoPage extends StatefulWidget {
  @override
  _MatchInfoPageSate createState() => _MatchInfoPageSate();
}

class _MatchInfoPageSate extends State<MatchInfoPage> {
  Autogenerated list;

  Future<Null> getData() async {
    String url =
        "https://api.cricapi.com/v1/matches?apikey=5d96e58a-40db-42e3-8bd9-a02881ea9a6d&offset=0";

    final response = await http.get(Uri.parse(url));

    if (response.statusCode == 200) {
      setState(() {
        list = Autogenerated.fromJson(json.decode(response.body));
        print("response.body.........................${response.body}");
        print("list.........................${list.data.length}");

        //return list;
      });
    }
  }

  @override
  void initState() {
    super.initState();
    getData();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text("Match List"),
        backgroundColor: Colors.red,
      ),
      body: Container(
          padding: EdgeInsets.all(12.0),
          child: GridView.builder(
            itemCount: list.data.length,
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 1, crossAxisSpacing: 4.0, mainAxisSpacing: 4.0),
            itemBuilder: (BuildContext context, int index) {
              print(
                  "autogenerated.data.length.....................${list.data.length}");
              print("index.....................$index");
              print("nDataList.....................${list.data[index].name}");

              return Container(
                child: Card(
                  color: Colors.white,
                  elevation: 5,

                  margin: EdgeInsets.only(
                      left: 5.0, bottom: 5.0, top: 5.0, right: 5.0),
                  child: Padding(
                    padding: EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Row(children: <Widget>[
                          Expanded(
                            flex: 1,
                            child: Container(
                                width: MediaQuery.of(context).size.width,
                                padding: EdgeInsets.all(2),
                                child: Column(children: <Widget>[
                                  Align(
                                    alignment: Alignment.centerLeft,
                                    child: Text(
                                      "${list.data[index].name}",
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 12,
                                        fontFamily: "Popp",
                                        color: Colors.black,
                                      ),
                                    ),
                                  )
                                ])),
                          ),
                        ]),
                        Row(children: <Widget>[
                          Expanded(
                            flex: 1,
                            child: Container(
                                width: MediaQuery.of(context).size.width,
                                padding: EdgeInsets.all(2),
                                child: Column(children: <Widget>[
                                  Align(
                                    alignment: Alignment.centerLeft,
                                    child: Text(
                                      "${list.data[index].date}",
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 12,
                                        fontFamily: "Popp",
                                        color: Colors.black,
                                      ),
                                    ),
                                  )
                                ])),
                          ),
                        ]),
                        SizedBox(
                          height: 10,
                        ),
                        Row(children: <Widget>[
                          Expanded(
                            flex: 1,
                            child: Container(
                                width: MediaQuery.of(context).size.width,
                                padding: EdgeInsets.all(2),
                                child: Column(children: <Widget>[
                                  Align(
                                    alignment: Alignment.centerLeft,
                                    child: Text(
                                      "${list.data[index].matchType}   ",
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 12,
                                        fontFamily: "Popp",
                                        color: Colors.black,
                                      ),
                                    ),
                                  )
                                ])),
                          ),

                        ]),      SizedBox(
                          height: 10,
                        ),
                        Row(children: <Widget>[

                          Expanded(
                            flex: 1,
                            child: Container(
                                width: MediaQuery.of(context).size.width * 0.20,
                                padding: EdgeInsets.all(2),
                                child: Column(children: <Widget>[
                                  Align(
                                    alignment: Alignment.centerLeft,
                                    child: Text(
                                      list.data[index].venue,
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 12,
                                        fontFamily: "Popp",
                                        color: Colors.black,
                                      ),
                                    ),
                                  )
                                ])),
                          ),
                        ]),
                        SizedBox(
                          height: 10,
                        ),
                        Row(children: <Widget>[
                          Expanded(
                            flex: 3,
                            child: Container(
                                width: MediaQuery.of(context).size.width,
                                padding: EdgeInsets.all(2),
                                child: Column(children: <Widget>[
                                  Align(
                                    alignment: Alignment.centerLeft,
                                    child: Text(
                                      list.data[index].dateTimeGMT,
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 12,
                                        fontFamily: "Popp",
                                        color: Colors.black,
                                      ),
                                    ),
                                  )
                                ])),
                          ),

                        ]),  SizedBox(
                          height: 10,
                        ),
                        Row(children: <Widget>[

                          Expanded(
                            flex: 1,
                            child: Container(
                                width: MediaQuery.of(context).size.width,
                                padding: EdgeInsets.all(2),
                                child: Column(children: <Widget>[
                                  Align(
                                    alignment: Alignment.centerLeft,
                                    child: Text(
                                      list.data[index].venue,
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 12,
                                        fontFamily: "Popp",
                                        color: Colors.black,
                                      ),
                                    ),
                                  )
                                ])),
                          ),
                        ]),
                        SizedBox(
                          height: 10,
                        ),
                        Row(children: <Widget>[
                          Expanded(
                            flex: 1,
                            child: Container(
                                width: MediaQuery.of(context).size.width,
                                padding: EdgeInsets.all(2),
                                child: Column(children: <Widget>[
                                  Align(
                                    alignment: Alignment.centerLeft,
                                    child: Text(
                                      list.data[index].venue,
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                        fontSize: 12,
                                        fontFamily: "Popp",
                                        color: Colors.black,
                                      ),
                                    ),
                                  )
                                ])),
                          ),
                        ]),
                        //   Text(nDataList.company.name),
                      ],
                    ),
                  ),
                ),
              );
            },
          )),
    ));
  }
}
